# Data Loading

### Import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mp

### A List of available DataFrame methods

In [2]:
dir(pd.DataFrame)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__unicode__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_apply_broadcast',
 '_apply_empty_result',
 '_apply_raw',
 '_apply_standard',
 '_at',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_const',
 '_combine_frame',
 '_combine_match_columns',
 '_combine_match_index',
 '_combine_series',
 '_combine_series_infer',
 '_compare_frame',
 '_compare_frame_evaluate',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_for_slice',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_ensure_valid_index',
 '_expand_axes',
 '_flex_compare_frame',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_numeric_data',
 '_get_valid_indices',
 '_get_value',
 '_get_values',
 '_getitem_array',
 '_getitem_column',
 '_getitem_frame',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_iat',
 '_iget_item_cache',
 '_iloc',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_dict',
 '_init_mgr',
 '_init_ndarray',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_loc',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_axis',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_frame_compat',
 '_unpickle_matrix_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'as_blocks',
 'as_matrix',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'axes',
 'between_time',
 'bfill',
 'blocks',
 'bool',
 'boxplot',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compound',
 'consolidate',
 'convert_objects',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_csv',
 'from_dict',
 'from_items',
 'from_records',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_value',
 'get_values',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'is_copy',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'ix',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'set_value',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'sortlevel',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_panel',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sparse',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'xs']

### Read CSV training file from the folder using pandas library

In [3]:
rtb = pd.read_csv("train.csv")
rtb.head()

,click,weekday,hour,bidid,userid,useragent,IP,region,city,adexchange,...,slotheight,slotvisibility,slotformat,slotprice,creative,bidprice,payprice,keypage,advertiser,usertag
0,0,5,22,b7bea80521fdecd95d2d761a38c91c3f09618066,2e880fb7d690cf7377b2e42e701728e3f3c0e4c1,windows_ie,125.37.175.*,2,2,2.0,...,200,2,0,5,a4f763f78ef3eedfe614263b94a8924e,238,5,0f951a030abdaedd733ee8d114ce2944,3427,NaN
1,0,1,20,4f51205475678f5a124bc76b2c54163bf8eaa7eb,3a1fe01360ff8100e7d006b83b77a3e4c01d928c,windows_chrome,171.36.92.*,238,239,1.0,...,250,FourthView,Na,0,10722,294,23,NaN,2821,NaN
2,0,3,13,b604e3fd054a658ab7ced4285ebf2ef54d2bd890,801d18a056b6fe6b06a794aef17fb0d6daff2414,windows_ie,59.46.106.*,40,41,2.0,...,250,2,0,5,798b2d49952d77f1eace9f23c210d0b5,238,24,0f951a030abdaedd733ee8d114ce2944,3427,"10052,10006,13866,10110"
3,0,6,23,0348beeae93e561584c3b50fc9e7746a33048ad7,0d6eaf2259699990e38a1fc5116f112070b9ecdc,windows_ie,114.250.226.*,1,1,1.0,...,600,2,1,0,cb7c76e7784031272e37af8e7e9b062c,300,25,bebefa5efe83beee17a3d245e7c5085b,1458,"13866,10063,10111"
4,0,5,6,268149c1789bce2bc9798ffd97ec431219bafeb3,a239d9bb642460d974ba67f85e63b8d3e214da0e,windows_ie,183.63.192.*,216,233,2.0,...,90,OtherView,Na,133,7330,277,133,NaN,2259,NaN

# Data Analysis whole dataset

In [4]:
rtb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2430981 entries, 0 to 2430980
Data columns (total 25 columns):
click             int64
weekday           int64
hour              int64
bidid             object
userid            object
useragent         object
IP                object
region            int64
city              int64
adexchange        float64
domain            object
url               object
urlid             float64
slotid            object
slotwidth         int64
slotheight        int64
slotvisibility    object
slotformat        object
slotprice         int64
creative          object
bidprice          int64
payprice          int64
keypage           object
advertiser        int64
usertag           object
dtypes: float64(2), int64(11), object(12)
memory usage: 463.7+ MB

In [5]:
#Number of rows where payprice == 0
print("Number of rows where payprice ==0")
print(len(rtb[rtb['payprice']==0]))
rtb[rtb['payprice']== 0].groupby(['slotid']).size()

Number of rows where payprice ==0
487

slotid
3175797632                       1
542871075                        1
ALLINONE_F_Width1                5
Auto_F_Rectangle                 3
Edu_F_Rectangle                  2
Ent_F_Upright                    1
Ent_F_bottom_Width               3
News_F_Rectangle                 1
News_F_Width1                    4
QQlive_SP_dsj_bottom_Width     296
QQlive_SP_dypd_bottom_Width     90
QQlive_SP_zypd_bottom_Width     77
Sports_F_Rectangle               2
Sports_F_Width1                  1
dtype: int64

In [6]:
#Number of Impressions in the data set
print("Number of Impressions in this data set")
Count_Imps = len(rtb)
print(Count_Imps)

Number of Impressions in this data set
2430981

In [7]:
#Number of clicks and non-clicks in the data set
click = rtb.groupby(['click']).size()
print('Number of clicks (1) and non-clicks (0) in the data set')

print(click)

Number of clicks (1) and non-clicks (0) in the data set
click
0    2429188
1       1793
dtype: int64

In [8]:
#Number of clicks in the data set
print("Number of Clicks in this data set")
Clicks = rtb.click.nonzero()
Count_Clicks = len(Clicks[0])
print(Count_Clicks)

Number of Clicks in this data set
1793

In [9]:
#CTR across the data set
CTR = (Count_Clicks / Count_Imps)
print(CTR)

0.0007375623256619447

In [10]:
#Total Pay Price across all bids in the data set
Total_Cost = rtb.loc[:,"payprice"].sum()
print("Total Pay Price across all bids in the data set")
print(Total_Cost)

Total Pay Price across all bids in the data set
189984608

In [11]:
#Mean CPM across all impressions in the dataset
Mean_CPM = rtb.loc[:,"payprice"].mean()
print("Mean CPM across all impressions in the dataset")
print(Mean_CPM)

Mean CPM across all impressions in the dataset
78.15141623895867

In [41]:
#Mean CPM across all impressions in the dataset
Mode_CPM = rtb.loc[:,"payprice"].mode()
print(Mode_CPM)

0    70
dtype: int64

In [12]:
#Mean bidprice across all impressions in the dataset
Mean_bidprice = rtb.loc[:,"bidprice"].mean()
print("Mean bid price across all impressions in the dataset")
print(Mean_bidprice)

Mean bid price across all impressions in the dataset
272.9620461862927

In [13]:
#Highest bidprice across all impressions in the dataset
Max_bidprice = rtb.loc[:,"bidprice"].max()
print("Maximum bid price across all impressions in the dataset")
print(Max_bidprice)

Maximum bid price across all impressions in the dataset
300

In [14]:
#Highest bidprice across all impressions in the dataset
Min_bidprice = rtb.loc[:,"bidprice"].min()
print("Minimum bid price across all impressions in the dataset")
print(Min_bidprice)

Minimum bid price across all impressions in the dataset
227

In [15]:
#Mean slotprice across all impressions in the dataset
Mean_slotprice = rtb.loc[:,"slotprice"].mean()
print("Mean slot price across all impressions in the dataset")
print(Mean_slotprice)

Mean slot price across all impressions in the dataset
26.71782502619313

In [16]:
#eCPC (mean CPC) across all impressions in the dataset
eCPC = (Mean_CPM/1000)/CTR
print("eCPC across all impressions in the dataset")
print(eCPC)

eCPC across all impressions in the dataset
105.95906748466258

In [40]:
#Show all clicked impressions
clicked_impressions = rtb.loc[rtb['click'] == 1]
click =

print(click.head())

         click  weekday  hour                                     bidid  \
1104         1        1    19  f9178e5b1b562648a5f63d36e423b0f26cec812d
4949         1        2    22  42c7568c0c07baa53e2ed2548d80fde568b1a4c1
8878         1        5     0  a305108883429eb515cc1246bb91a1e64a537476
9790         1        2    19  c22254a0bad8028de4a6cdf51f502f6cf109c610
10000        1        2    17  e42e60785c6f03678e8bdc7f5b5e3c054b902ae5
11683        1        6    22  50e7e9404d75a9fb1bb6411606cdbecca4e20388
12733        1        6    23  dc20e4adcdba3fb5f531f7f4e62ff08fcec39b66
13025        1        4    22  54b1bfec19fe389478ed2a77f184bf4c31eaf1d1
13783        1        6    17  9465de4fb19b6be613fc93e1014dc3c2e2a7de20
14405        1        5    13  451a15d5edc8e439872f92d9fe4e99337e2fe93e
16815        1        5     0  dbaf05567b8c401f22d6bda65debd863ce5358b3
17831        1        6    11  c925ed48d52756fc7bb65ae7c71b38c408ad491a
18797        1        6    10  49b97a294f338e40055ac896c79130eaa44b7b15
19088        1        1     7  5d0021f70701f3521e41ac77472d684cafe38ed1
21591        1        0    14  2eb7cc31acb1ecf25d5124597fd91af8ceef40a4
22737        1        0    10  c5507f3722bd99f409c37bc4698d07aab2c1ae11
22992        1        5    23  b5fb5a0ddf16c68f515d9d209c9a66ed4e5155ce
24205        1        0    19  9174125c05635cbc0fc5360cf23e1dd62ea0281b
24614        1        4    21  06937437fd16d1829b8e8c8a8f3566b713540ebb
26760        1        6    15  d175a560ec8edc3bb62493aa502d42780eaa58b2
27789        1        1    21  06e208b2b8cbe058ea4805771c01d47db52acfbf
34413        1        6     9  96870f63dae5db02fb0c676edb20b193d4a3fec7
37494        1        0    10  1b4c5faf305c6f23bdeddfbb85424297779dbbaf
38670        1        1    14  704ce1daff659b6e8707516ec266a77b9a1a5cc6
40552        1        2    17  22b34d342c69fdb0bd35863b602d850308422cbc
40819        1        2    11  ea62bdfe00e4e2cc5991b18396560a963211f473
41765        1        6    10  8c1d14742eae74e9e89b82cc8d8399c3ca892ec3
42248        1        6    17  8203c82cf2aa425de88eae744ba716855bd69453
44039        1        3    11  a638f9a49e22dcbddf15acb5b8206160f2cbc2ce
44521        1        5     1  f03a9d595ea7ac1984e41537d2e557af1822aa9a
...        ...      ...   ...                                       ...
2282397      1        2    17  d14875fbf45f84bf95a39c1e5ccbed02e5295065
2282668      1        0    18  a34c79efbb8d8a713a6e1cacad4d75af9d412f14
2287076      1        4    19  a79fff38098b999169a7f88e388b42c300ed6e8e
2300118      1        4    20  1bf3e99b29c6b44ba6e293a0f7dd551917728176
2305965      1        2    15  9ffeb6dd286400018650bbabbe72014b33368892
2311503      1        5     0  4ba8104c1fac8e9d99c8db9d141153991a614db2
2314066      1        0     8  eded5b310e35d96db661ee494ce2d4d9023ce144
2315760      1        3     0  3ce53f6a9973df8b99d3ea07a8c208c5c1844915
2318244      1        4    22  ac3d4b6650d08924b8a730743dfdc544ec9e8fb5
2319431      1        6    10  7231aca33ccafd102a695db0a93ec4dcc6e73896
2324510      1        0    18  8862c3d7284bd0bc4b59688390de11f6089df45d
2326586      1        1    20  d89ea1699e955ab88d6a64ff491c8615b136439f
2330843      1        2    15  bfad8ba96886348f73f3373aa68fe4ecbe7468d6
2341007      1        3    18  8ff447bf2f68ce9edd24237e396c0c448f56f3c0
2343305      1        2    21  56a4e6e0db9251c2c41510e3fb0c51417513ee6f
2347368      1        3    13  48eaae28a6dfec5eb5211ab084d3a836f492aec2
2350147      1        1    19  bce4108a3273a282dc1b7636f1918ebedb8507f3
2356785      1        3    17  5f1735d252b74ab2e45fcd691f877654ddc5ab96
2364612      1        2    19  a41d834fd08c3b7ee27edb04928e232473d2b318
2365483      1        1    13  d1dc9c2e1bcdb155600899b205a87a0200b9c5c7
2374472      1        4    18  16bc43e5a682587707ea2860613f6d2540990f97
2374507      1        4    11  d82b221ba6e33050d930aafc016c8a3bd4658084
2379492      1        3    16  66f003699a9e5dd7ff149693df3a1e5573a98745
2387360      1        1     8  a5592c4e25763027bfe1fe18cc5c611d810b2bf5
2395842      1        1    11  0b3a9ab7c96691e72b9b738b712b744efbebfed2
2399896      1        5     0  bb254df8973f8378919a5053139ac55d4bb6b463
2405586      1        0    15  dfd3c31b4a6811074bd916ef22cf12ffe4498dd8
2415911      1        4    18  7557e68e7f33be8d0e9d8f87db8c503db5de31fe
2417205      1        2    19  5c5a0e51fb39eac2b14d37a2724ef7806eb16022
2419465      1        0    19  f1c8128707dae729411a9156e459726044f1e8ec

                                           userid       useragent  \
1104     ca22bf856b6c720994a95302f5ce71e0d6d5d416      windows_ie
4949     9ed92c2038dfbaaf3ec37a48155e8712777cb21d      windows_ie
8878     efbec188a3a7684e898747dd6cbe1194c7d89319  android_safari
9790     875ee65d08205ed37fd33b12de85cc86f1ae2aae  android_safari
10000    4cadd1388b905c04c641106ee3568358b655d92b  windows_chrome
11683    f259cb09328b18779dc7e420867a7aedc14cd158  windows_chrome
12733    21469ed0e959bc155591e368d7c6d26003087fb5  windows_chrome
13025    1f28f771096499bf5eecd262baa0a645bdad3106      windows_ie
13783    05882afa283f90567b8d28e1c15e8bab3a972eb7  windows_chrome
14405    98dc8140af70d44e1b53012871c3d07f4e419887  android_safari
16815    1c2ad0bd5778c1e7a127f8d9840c2a2dddf2b8a5       mac_other
17831    ad141adbc22a57989280ee75b88a8baa18c6ec6e  windows_chrome
18797    12f776973c8fb0f7be579f70f184672b903995f7  android_safari
19088    39e097da170d53b4a0623002c8ea6d952c1ee874  windows_chrome
21591    dc40f9a9f4aad86e9e39154ff87fd15e34859e66      windows_ie
22737    f1c6a285f27ea9b355a647671ec359b31d27a1d6      windows_ie
22992    1ac7a85bc11e526b55ae19dcb6d1ced4d7c8faf7  windows_chrome
24205    b05655b07d9dbe6ae64d8d26ad80ffb29af0aca6  windows_chrome
24614    da503e8b5200678853cb84bac7d48dc33e4893fe      mac_safari
26760    a4cf33eea3b3c919f1efea2cb4ce0014bcd8fd7f      windows_ie
27789    c9cf6a364f3068ffbdd71e508cc7e933ca8232b8      windows_ie
34413    e7250f6cc4b9afab164e44a3cd0f701c587fb788      windows_ie
37494    dca7b0c8ef2aa551307db9ffb5e8ed1ac0e5242e      windows_ie
38670    3f5e209e953534c6dc4a670d41816f2d51b3c88a      windows_ie
40552    3f192a5b952f1f7804675fe14f96c1fe5cca2815  android_safari
40819    ae34e763fe1753ce8992ba923bd3e4dcf03725cd      windows_ie
41765    f47ea7d232e63d509105fccb0378d207b14b9885  windows_chrome
42248    90502a538e140042c3d1b75ce98f92a3e75818a9      windows_ie
44039    ad8549e45b5e5e7235e346b94ab4e5d93b13cf85  android_safari
44521    534442a33b6c473f926d639be001a4a81baaf849      windows_ie
...                                           ...             ...
2282397  8f9658aa2a76f03a848a610f44d7c714ddc306d3  android_safari
2282668  57937ca6bc0151cfeea52e4c927a6b231545ce6a      windows_ie
2287076  1746bdcb5b226ca3366c4fb8ad62201abecb61bf      windows_ie
2300118  146779e6a2eefbc6d8fa8076eb6682ee5f84880d      windows_ie
2305965  b27fe1507620f7d0e868cb72080b44a0e02d0cc3  windows_chrome
2311503  7c36b82d106463c24d98c36605fafd5731b6487f  windows_chrome
2314066  16e364fe66ec4b981064247bf8b272eed7830fdc  android_safari
2315760  5d2226d49ffb261f0f3da1c1de3a99650d5edaeb      windows_ie
2318244  80d240b917aec7c2de64b430296148ab4029b8c0      windows_ie
2319431  05ded9203279b29f5014bbf01b0c798d550be16f      windows_ie
2324510  02c087ce868c107e9205ee0010ae6a7f74a9e9e9      windows_ie
2326586  7c9e54a4dc9a5d07d9316257ea1ecf62dd79eac3      mac_safari
2330843  64aed8cdb627faa88f0d29473b75f2c1cf95f398      windows_ie
2341007  14eef529d61cc16a69ebbb557c4ba1129523daab  android_safari
2343305  47e37f24d0884b01214840ff264dccac4515938a      windows_ie
2347368  270952a2dcadc3034c1b28e6c5908767aa7a486a      windows_ie
2350147  9759430cab21e469e8e1602c1b432f10aa8762bf      windows_ie
2356785  49b23024bc66330c10d77b6b7324674c7438bd5a       mac_other
2364612  e84e87d6d7ff6f315fd33452424bd44da3a16a95  android_safari
2365483  dfa2d15f43262ee1822b379bc8cd7fd408cbab5d  windows_chrome
2374472  3eb65d5f4c4bdeed2b9948c00e23b9daf087e8d3  android_safari
2374507  69168729d14a7f96ce00d9ba6bc57445e6e35185      windows_ie
2379492  797bf6905e02474baf11dcbb59843874a281a615  android_safari
2387360  65966e8165fda9c660711261eec3bdda963d2153      windows_ie
2395842  abba24a4784d25bfdd5d037e79218675fbf6f239  windows_chrome
2399896  517aa352c72879bbd2d904323815a802fff295b9      mac_safari
2405586  1f5217f3df9c334a158177601224d25a334f4adf  windows_chrome
2415911  f29c6a5f0fba131b3bfb72ed1afd5c463d575ba5      windows_ie
2417205  1b31d9f969e9bf6a3454ad902525fd29f8ac328e  android_safari
2419465  fa3d76fbfb95a9ec85369f8db7b27de5bd84b682  windows_chrome

                    IP  region  city  adexchange  \
1104        114.93.5.*      79    79         3.0
4949       116.5.161.*     216   228         1.0
8878      117.136.24.*     201   202         1.0
9790      119.22.194.*       3     4         NaN
10000     14.134.245.*     368   373         1.0
11683      123.84.51.*     201   214         2.0
12733     113.132.11.*     333   334         1.0
13025    221.206.142.*      65    75         2.0
13783      171.35.40.*     134   141         2.0
14405     120.11.208.*       3    12         1.0
16815     49.113.242.*     374   375         1.0
17831     125.79.167.*     124   128         1.0
18797     96.239.124.*       0     0         1.0
19088      116.95.29.*      27    31         4.0
21591      218.24.61.*      40    50         2.0
22737    221.205.216.*      15    16         3.0
22992     110.166.76.*     359   360         1.0
24205      49.117.49.*     374   387         2.0
24614      116.54.92.*     308   309         1.0
26760        27.10.8.*     275   275         2.0
27789    124.165.213.*      15    26         1.0
34413      120.90.17.*      79    79         2.0
37494     61.157.144.*     276   282         3.0
38670    219.138.108.*     183   190         4.0
40552     117.136.24.*     201   202         NaN
40819      183.36.40.*     216   223         2.0
41765    122.206.190.*     164   165         3.0
42248      218.6.164.*     276   281         3.0
44039     117.147.40.*      94    97         1.0
44521    113.108.205.*     216   217         1.0
...                ...     ...   ...         ...
2282397    14.18.250.*     216   216         NaN
2282668    27.16.225.*     183   184         1.0
2287076   222.87.144.*     298   300         2.0
2300118  123.184.211.*      40    41         1.0
2305965     60.6.142.*       3     8         3.0
2311503  101.130.153.*       0     0         1.0
2314066     1.86.231.*     333   334         1.0
2315760  175.189.133.*     183   184         1.0
2318244   218.15.161.*     216   228         1.0
2319431      60.4.46.*       3     9         1.0
2324510    59.54.231.*     134   144         2.0
2326586   124.42.247.*     216   219         1.0
2330843  180.104.253.*      80    85         2.0
2341007   60.175.194.*     106   118         NaN
2343305    171.34.41.*     134   135         1.0
2347368  221.213.202.*     308   316         1.0
2350147  180.111.160.*      80    81         1.0
2356785  180.106.148.*      80    85         1.0
2364612   175.19.114.*      55    56         NaN
2365483   183.239.75.*     216   216         1.0
2374472   27.198.191.*     146   154         NaN
2374507     117.44.5.*     134   141         2.0
2379492   182.245.68.*     308   309         NaN
2387360    14.20.175.*     216   219         3.0
2395842    218.13.50.*     216   222         1.0
2399896  180.121.126.*      80    86         1.0
2405586   112.238.11.*     146   152         2.0
2415911   114.82.246.*      79    79         2.0
2417205    122.4.142.*     146   154         NaN
2419465  112.112.223.*     308   309         2.0

                               ...                         slotheight  \
1104                           ...                                 90
4949                           ...                                280
8878                           ...                                250
9790                           ...                                 50
10000                          ...                                250
11683                          ...                                250
12733                          ...                                280
13025                          ...                                 90
13783                          ...                                 90
14405                          ...                                250
16815                          ...                                 90
17831                          ...                                250
18797                          ...                                250
19088                          ...                                250
21591                          ...                                280
22737                          ...                                250
22992                          ...                                 90
24205                          ...                                 90
24614                          ...                                280
26760                          ...                                 90
27789                          ...                                 90
34413                          ...                                250
37494                          ...                                250
38670                          ...                                 90
40552                          ...                                 50
40819                          ...                                 90
41765                          ...                                 90
42248                          ...                                 90
44039                          ...                                250
44521                          ...                                 90
...                            ...                                ...
2282397                        ...                                 50
2282668                        ...                                280
2287076                        ...                                250
2300118                        ...                                 90
2305965                        ...                                250
2311503                        ...                                250
2314066                        ...                                 90
2315760                        ...                                250
2318244                        ...                                600
2319431                        ...                                 60
2324510                        ...                                280
2326586                        ...                                250
2330843                        ...                                600
2341007                        ...                                 50
2343305                        ...                                250
2347368                        ...                                600
2350147                        ...                                250
2356785                        ...                                 90
2364612                        ...                                 50
2365483                        ...                                 90
2374472                        ...                                 50
2374507                        ...                                250
2379492                        ...                                 50
2387360                        ...                                 90
2395842                        ...                                250
2399896                        ...                                 90
2405586                        ...                                280
2415911                        ...                                600
2417205                        ...                                 50
2419465                        ...                                280

        slotvisibility  slotformat slotprice  \
1104                 0           0        80
4949                 0           1         0
8878                 1           5         0
9790         FirstView          Na       160
10000                1           1         0
11683                1           0         5
12733                2           1         0
13025                2           0         5
13783                1           0         5
14405                1           5         0
16815                0           1         0
17831                0           5         0
18797                1           5         0
19088       SecondView          Na        30
21591                2           0         5
22737                0           0        50
22992                2           1         0
24205        OtherView          Na         5
24614                2           1         0
26760                2           0         5
27789                0           1         0
34413                2           0         5
37494                0           0        31
38670        FirstView          Na         0
40552        FirstView          Na         6
40819                2           0         5
41765                0           0        70
42248                0           0        80
44039                1           5         0
44521                2           1         0
...                ...         ...       ...
2282397      FirstView          Na         6
2282668             Na          Na         0
2287076              2           0         5
2300118              0           1         0
2305965             Na          Na        50
2311503              1           1         0
2314066              1           1         0
2315760              1           1         0
2318244              2           1         0
2319431      ThirdView          Na         0
2324510              2           0         5
2326586              1           1         0
2330843      OtherView          Na         5
2341007      FirstView          Na         6
2343305              2           1         0
2347368              0           1         0
2350147      FirstView          Na         0
2356785             Na          Na         0
2364612      FirstView          Na         6
2365483              1           1         0
2374472      FirstView          Na         6
2374507              1           0         5
2379492      FirstView          Na         6
2387360             Na          Na        70
2395842             Na          Na         0
2399896              0           1         0
2405586              2           0         5
2415911              0           0         5
2417205      FirstView          Na        15
2419465              2           0         5

                                 creative  bidprice payprice  \
1104     86c2543527c86a893d4d4f68810a0416       300       80
4949     77819d3e0b3467fe5c7b16d68ad923a1       300       65
8878     44966cc8da1ed40c95d59e863c8c75f0       300      101
9790                                11908       277      160
10000    44966cc8da1ed40c95d59e863c8c75f0       300      108
11683    7097e4210dea4d69f07f0f5e4343529c       300       95
12733    77819d3e0b3467fe5c7b16d68ad923a1       300      300
13025    48f2e9ba15708c0146bda5e1dd653caa       300       38
13783    48f2e9ba15708c0146bda5e1dd653caa       300      201
14405    449a22cd91d9042eda3d3a1b89a22ea8       227      100
16815    cc9b344e950b4f8c2b96537174a343b7       227      103
17831    44966cc8da1ed40c95d59e863c8c75f0       300      228
18797    00fccc64a1ee2809348509b7ac2a97a5       227       74
19088                               10722       294       31
21591    ff5123fb9333ca095034c62fdaaf51aa       300      127
22737    a499988a822facd86dd0e8e4ffef8532       300       50
22992    fa8f0532dd5144b5fa748459e8d90b49       227      160
24205                               10719       277       61
24614    77819d3e0b3467fe5c7b16d68ad923a1       300       15

In [29]:
#Show average prices for clicked impressions
average_bidprice = clicked_impressions.loc[:,'bidprice'].mean()
average_payprice = clicked_impressions.loc[:,'payprice'].mean()
print("Average pay prices for clicked impressions")
print(average_payprice)
print("Average bid prices for clicked impressions")
print(average_bidprice)

print(clicked_byprice)

Average pay prices for clicked impressions
105.46402677077523
Average bid prices for clicked impressions
273.2269938650307
<pandas.core.groupby.DataFrameGroupBy object at 0x000000000F7AFEF0>

# Data Analysis by Advertisers

In [19]:
# Look at click and non click for each advertiser
df_click = rtb.groupby(['advertiser','click']).size().reset_index(name ='click_or_no_click')
df_click

    advertiser  click  click_or_no_click
0         1458      0             491968
1         1458      1                385
2         2259      0             133630
3         2259      1                 43
4         2261      0             110086
5         2261      1                 36
6         2821      0             211235
7         2821      1                131
8         2997      0              49612
9         2997      1                217
10        3358      0             264754
11        3358      1                202
12        3386      0             454721
13        3386      1                320
14        3427      0             402534
15        3427      1                272
16        3476      0             310648
17        3476      1                187

In [20]:
# Calculate number of bids for each advertisers

bid_counts = rtb.groupby(['advertiser']).agg({'bidid':'size'}).rename(columns={'bidid':'number_of_bids'})
bid_counts_sorted = bid_counts.sort_values(by=['number_of_bids'], ascending= False)
bid_counts_sorted

            number_of_bids
advertiser
1458                492353
3386                455041
3427                402806
3476                310835
3358                264956
2821                211366
2259                133673
2261                110122
2997                 49829

In [21]:
advertisers_grouped = rtb.groupby(['advertiser']).mean()
advertisers_grouped

,click,weekday,hour,region,city,adexchange,urlid,slotwidth,slotheight,slotprice,bidprice,payprice
advertiser,,,,,,,,,,,,
1458,0.000782,2.995215,14.071445,144.312473,149.355330,2.027846,NaN,596.508249,204.694863,28.275305,300.000000,68.992646
2259,0.000322,3.112895,10.480853,216.000000,222.848391,1.952249,NaN,506.677803,191.845399,24.529157,288.078939,92.974931
2261,0.000327,4.403498,11.964285,139.525109,143.821925,1.993889,NaN,498.512577,217.682570,27.127967,287.877981,89.662184
2821,0.000620,0.656827,16.050997,141.102732,145.679632,2.764513,NaN,611.500809,185.094008,23.308943,290.224894,89.077922
2997,0.004355,3.531116,17.154227,153.235064,157.645748,NaN,NaN,320.000000,50.000000,33.779586,277.000000,62.800116
3358,0.000762,3.222120,12.144062,152.834255,157.709752,1.672632,NaN,561.837830,197.195572,17.419896,232.981091,84.720599
3386,0.000703,3.006035,13.779347,145.088774,149.961441,2.200648,NaN,580.857817,183.502366,29.499239,300.000000,76.766320
3427,0.000675,3.116825,13.722705,146.293370,151.283074,2.138687,NaN,621.612533,177.090783,29.293809,236.388882,75.616329
3476,0.000602,2.748860,12.490978,144.622372,149.276166,2.104564,NaN,574.649168,190.843245,26.748307,247.856152,76.950083

In [22]:
#Number of advertisers in the data set
print('Number of advertisers in the data set')
print(len(advertisers_grouped), 'Advertisers')

Number of advertisers in the data set
9 Advertisers

# Data Analysis by Weekday

In [23]:
# Look at click and non click for each weekday
df_click_no_click = rtb.groupby(['weekday','click']).size().reset_index(name ='click_or_no_click').sort_values(by=['click_or_no_click'], ascending= False)
df_click = df_click_no_click[df_click_no_click['click'] == 1].reset_index(drop=True).sort_values(by=['click'], ascending= False)
df_click

   weekday  click  click_or_no_click
0        2      1                286
1        3      1                283
2        0      1                271
3        4      1                264
4        1      1                249
5        5      1                247
6        6      1                193

# Data Analysis by Hour

In [24]:
# Look at click and non click for each day hour
df_click = rtb.groupby(['hour','click']).size().reset_index(name ='click_or_no_click').sort_values(by=['click_or_no_click'], ascending= False)
df_click

    hour  click  click_or_no_click
0      0      0             177041
36    18      0             154993
44    22      0             153618
32    16      0             149683
30    15      0             148775
34    17      0             143358
26    13      0             140329
28    14      0             132691
24    12      0             128531
22    11      0             128483
20    10      0             127249
40    20      0             121137
38    19      0             120199
46    23      0             113636
42    21      0             101983
18     9      0              82357
16     8      0              69166
2      1      0              60298
14     7      0              46458
4      2      0              34338
6      3      0              33111
12     6      0              23041
10     5      0              19851
8      4      0              18862
37    18      1                156
35    17      1                146
45    22      1                138
33    16      1                124
1      0      1                122
39    19      1                119
27    13      1                114
47    23      1                102
31    15      1                 92
43    21      1                 92
41    20      1                 91
29    14      1                 81
25    12      1                 71
21    10      1                 70
23    11      1                 65
19     9      1                 42
3      1      1                 33
15     7      1                 32
17     8      1                 31
5      2      1                 23
11     5      1                 16
7      3      1                 15
9      4      1                 12
13     6      1                  6

# Data Analysis by AdExchange

In [25]:
# Look at click and non click for each weekday
df_click = rtb.groupby(['adexchange','click']).size().reset_index(name ='click_or_no_click').sort_values(by=['click_or_no_click'], ascending= False)
df_click

   adexchange  click  click_or_no_click
4         3.0      0             818894
2         2.0      0             763042
0         1.0      0             717683
6         4.0      0              79957
1         1.0      1                588
5         3.0      1                564
3         2.0      1                386
7         4.0      1                 38

# Data Analysis by UserAgent

In [26]:
# Look at click and non click for each weekday
df_click = rtb.groupby(['useragent','click']).size().reset_index(name ='click_or_no_click').sort_values(by=['click_or_no_click'], ascending= False)
df_click

           useragent  click  click_or_no_click
43        windows_ie      0            1460721
39    windows_chrome      0             794222
8     android_safari      0              61279
29        mac_safari      0              37280
41   windows_firefox      0              22261
52  windows_theworld      0              14020
48     windows_other      0              11121
27         mac_other      0               7761
45   windows_maxthon      0               7412
47     windows_opera      0               2197
22        mac_chrome      0               1938
6      android_other      0               1809
36       other_other      0               1651
50    windows_safari      0               1612
15      linux_chrome      0                979
44        windows_ie      1                944
24       mac_firefox      0                744
0     android_chrome      0                478
5      android_opera      0                406
17     linux_firefox      0                355
40    windows_chrome      1                350
13        ios_safari      0                349
9     android_safari      1                298
21      linux_safari      0                134
30        mac_safari      1                121
35       other_opera      0                103
20       linux_other      0                 52
38      other_safari      0                 47
11         ios_other      0                 38
4    android_maxthon      0                 37
25       mac_maxthon      0                 32
19       linux_opera      0                 24
28         mac_other      1                 24
26         mac_opera      0                 23
2    android_firefox      0                 20
18          linux_ie      0                 17
32      other_chrome      0                 16
34          other_ie      0                 14
10     android_sogou      0                 14
31         mac_sogou      0                 12
49     windows_other      1                 12
7      android_other      1                 12
42   windows_firefox      1                 10
51     windows_sogou      0                  5
53  windows_theworld      1                  5
46   windows_maxthon      1                  4
16      linux_chrome      1                  4
3         android_ie      0                  4
23        mac_chrome      1                  3
14        ios_safari      1                  2
1     android_chrome      1                  2
12         ios_other      1                  1
37       other_other      1                  1
33     other_firefox      0                  1